### ISSUE TITLE
Sugar content?

### ISSUE THREAD

**Issue by jebyrnes** [AlexGustafsson/systembolaget-api-data#1]
This is AMAZING!

I was wondering, can you add sugar content (either sugarContentText or Sockerhalt) to the scrape? Would be very useful for a variety of analyses!

**Comment by AlexGustafsson** [comment]
Thank you for the kind words! Unfortunately Systembolaget has decided to close their APIs again due to companies abusing it against the terms. This change is in effect since November first. I haven’t had the time to investigate further what it means for this project (and the actual code to fetch it which is available here:  https://github.com/AlexGustafsson/systembolaget-api). My goal is to keep this project going, but it might be a while before I’m able to update the backing code.

**Comment by jebyrnes** [comment]
Oh no! Well, if you try it, let me know! I was also looking into whether it would be possible to scrape it from web pages, but, that seemed a little overboard. Thanks! Hope it works out. Stupid abuse of such cool tools.

**Comment by AlexGustafsson** [comment]
The tool has now been updated to include all the data available to users on the official website. To run it yourself, check out https://github.com/AlexGustafsson/systembolaget-api. For up to date data, wait for the bot to update this repository.

Closing.
